# Spring
spring:
  application:
    name: api-gateway
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

# Server
server:
  port: 8080
  
# Management
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: false
        
# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# Zuul
zuul:
  prefix: /api
  ignoredServices: "*"
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
      sensitive-headers:
      strip-prefix: false
    account-service:
      path: /accounts/**
      service-id: account-service
      sensitive-headers:
      strip-prefix: false
    access-service:
      path: /access/**
      service-id: access-service
      sensitive-headers:
      strip-prefix: false
    transaction-service:
      path: /transactions/**
      service-id: transaction-service
      sensitive-headers:
      strip-prefix: false
      
# Ribbon Timeout
ribbon:
  ReadTimeout: 100000000
  connect-timeout: 500000000
  
# Clients
api:
  client:
    auth-service:
      url: localhost:9000/auth
    account-service:
      url: localhost:9010/accounts
    transaction-service:
      url: localhost:9030/transactions

# Log
logging:
  level:
    ROOT: info
    org.springframework.web: info
    pay.pimpo: debug
    pay.pimpo.commons.clients.AuthClient: debug
  file:  /tmp/logs/api-gateway.log
      