# Spring
spring:
  profiles: default
  application:
    name: access-service
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo

# Server
server:
  port: 9020
  use-forward-headers: false
  servlet:
    context-path: /access

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
# Clients
api:
  client:
    auth-service:
      url: localhost:9000/auth
    account-service:
      url: localhost:9010/accounts
    transaction-service:
      url: localhost:9030/transactions

# Log
logging:
  level:
    ROOT: info
    org.springframework.web: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    pay.pimpo: debug
  file:  /tmp/logs/access-service.log
