# Spring
spring:
  profiles: default
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: always
    continue-on-error: true
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
      use-new-id-generator-mappings: false
  # Spring Cloud tem conflitos de referência circular com Spring Data Source
  # https://github.com/spring-cloud/spring-cloud-commons/issues/355
  cloud:
    refresh:
      refreshable: none

# Server
server:
  port: 9010
  use-forward-headers: false
  servlet:
    context-path: /account

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

# Log
logging:
  level:
    ROOT: info
    org.springframework.web: info
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    pay.pimpo: debug
  file:  /tmp/logs/account-service.log
