# Spring
spring:
  profiles: default
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: always
    continue-on-error: true
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
      use-new-id-generator-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
  # Spring Cloud tem conflitos de referência circular com Spring Data Source
  # https://github.com/spring-cloud/spring-cloud-commons/issues/355
  cloud:
    refresh:
      refreshable: none

# Server
server:
  port: 9000
  use-forward-headers: false
  servlet:
    context-path: /auth

# Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
# Clients
api:
  client:
    auth-service:
      url: localhost:9000/auth
    account-service:
      url: localhost:9010/accounts
    transaction-service:
      url: localhost:9030/transactions

# Log
logging:
  level:
    ROOT: info
    org.springframework.web: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    pay.pimpo: debug
  file:  /tmp/logs/auth-service.log
